spring:
  profiles:
    active: dev

---
server:
  port: 8080

logging:
  level:
    root: info

spring:
  profiles: dev

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://jarvis1.clzkjwwf2qt9.ap-northeast-2.rds.amazonaws.com/team_rest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username:
      password:
    initialization-mode: always
    schema: classpath:sql/schema.sql

  cache:
    type: redis

  redis:
#    port: 6379
#    host: localhost
#    password: null



